//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giscada.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://66.240.223.249", ConfigurationName="ServiceReference1.WebServiceClienteSoap")]
    public interface WebServiceClienteSoap {
        
        // CODEGEN: Generating message contract since element name User from namespace http://66.240.223.249 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://66.240.223.249/ReceiveDataXML", ReplyAction="*")]
        giscada.ServiceReference1.ReceiveDataXMLResponse ReceiveDataXML(giscada.ServiceReference1.ReceiveDataXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://66.240.223.249/ReceiveDataXML", ReplyAction="*")]
        System.Threading.Tasks.Task<giscada.ServiceReference1.ReceiveDataXMLResponse> ReceiveDataXMLAsync(giscada.ServiceReference1.ReceiveDataXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveDataXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveDataXML", Namespace="http://66.240.223.249", Order=0)]
        public giscada.ServiceReference1.ReceiveDataXMLRequestBody Body;
        
        public ReceiveDataXMLRequest() {
        }
        
        public ReceiveDataXMLRequest(giscada.ServiceReference1.ReceiveDataXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://66.240.223.249")]
    public partial class ReceiveDataXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Id;
        
        public ReceiveDataXMLRequestBody() {
        }
        
        public ReceiveDataXMLRequestBody(string User, string Pass, string Id) {
            this.User = User;
            this.Pass = Pass;
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveDataXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveDataXMLResponse", Namespace="http://66.240.223.249", Order=0)]
        public giscada.ServiceReference1.ReceiveDataXMLResponseBody Body;
        
        public ReceiveDataXMLResponse() {
        }
        
        public ReceiveDataXMLResponse(giscada.ServiceReference1.ReceiveDataXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://66.240.223.249")]
    public partial class ReceiveDataXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReceiveDataXMLResult;
        
        public ReceiveDataXMLResponseBody() {
        }
        
        public ReceiveDataXMLResponseBody(string ReceiveDataXMLResult) {
            this.ReceiveDataXMLResult = ReceiveDataXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceClienteSoapChannel : giscada.ServiceReference1.WebServiceClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClienteSoapClient : System.ServiceModel.ClientBase<giscada.ServiceReference1.WebServiceClienteSoap>, giscada.ServiceReference1.WebServiceClienteSoap {
        
        public WebServiceClienteSoapClient() {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        giscada.ServiceReference1.ReceiveDataXMLResponse giscada.ServiceReference1.WebServiceClienteSoap.ReceiveDataXML(giscada.ServiceReference1.ReceiveDataXMLRequest request) {
            return base.Channel.ReceiveDataXML(request);
        }
        
        public string ReceiveDataXML(string User, string Pass, string Id) {
            giscada.ServiceReference1.ReceiveDataXMLRequest inValue = new giscada.ServiceReference1.ReceiveDataXMLRequest();
            inValue.Body = new giscada.ServiceReference1.ReceiveDataXMLRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pass = Pass;
            inValue.Body.Id = Id;
            giscada.ServiceReference1.ReceiveDataXMLResponse retVal = ((giscada.ServiceReference1.WebServiceClienteSoap)(this)).ReceiveDataXML(inValue);
            return retVal.Body.ReceiveDataXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<giscada.ServiceReference1.ReceiveDataXMLResponse> giscada.ServiceReference1.WebServiceClienteSoap.ReceiveDataXMLAsync(giscada.ServiceReference1.ReceiveDataXMLRequest request) {
            return base.Channel.ReceiveDataXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<giscada.ServiceReference1.ReceiveDataXMLResponse> ReceiveDataXMLAsync(string User, string Pass, string Id) {
            giscada.ServiceReference1.ReceiveDataXMLRequest inValue = new giscada.ServiceReference1.ReceiveDataXMLRequest();
            inValue.Body = new giscada.ServiceReference1.ReceiveDataXMLRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pass = Pass;
            inValue.Body.Id = Id;
            return ((giscada.ServiceReference1.WebServiceClienteSoap)(this)).ReceiveDataXMLAsync(inValue);
        }
    }
}
